version: 1
builder:
  configs:
    - documentation_targets:
        - ApplicationProtobuf
        - HomomorphicEncryption
        - HomomorphicEncryptionProtobuf
        - PIRGenerateDatabase
        - PIRProcessDatabase
        - PIRShardDatabase
        - PNNSGenerateDatabase
        - PNNSProcessDatabase
        - PrivateInformationRetrieval
        - PrivateNearestNeighborSearch
      swift_version: 6.0
