version: 1
builder:
  configs:
    - documentation_targets:
        - HomomorphicEncryption
        - HomomorphicEncryptionProtobuf
        - PIRGenerateDatabase
        - PIRProcessDatabase
        - PIRShardDatabase
        - PNNSGenerateDatabase
        - PNNSProcessDatabase
        - PrivateInformationRetrieval
        - PrivateInformationRetrievalProtobuf
        - PrivateNearestNeighborSearch
        - PrivateNearestNeighborSearchProtobuf
      swift_version: 6.0
