disabled_rules:
  - cyclomatic_complexity
  - file_length
  - function_body_length
  - identifier_name
  - opening_brace  # conflicts with swiftformat
  - todo
  - trailing_comma  # conflicts with swiftformat
  - type_body_length
  - vertical_parameter_alignment_on_call  # conflicts with swiftformat
  - file_header  # pre-commit deals with license header
  - raw_value_for_camel_cased_codable_enum  # conflicts with swiftformat
  - extension_access_modifier

excluded:
  - "**/*pb.swift"
  - "**/DoubleWidthUInt.swift"
  - "**/.build/"

type_name:
  allowed_symbols: "_"

line_length:
  warning: 120
  ignores_urls: true

closure_body_length:
  warning: 40

opt_in_rules:
  - accessibility_label_for_image
  - accessibility_trait_for_button
  - anonymous_argument_in_multiline_closure
  - array_init
  - attributes
  - balanced_xctest_lifecycle
  - closure_body_length
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - comma_inheritance
  - conditional_returns_on_newline
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - contains_over_range_nil_comparison
  - convenience_type
  - direct_return
  - discarded_notification_center_observer
  - discouraged_assert
  - discouraged_none_name
  - discouraged_object_literal
  - discouraged_optional_boolean
  - empty_collection_literal
  - empty_count
  - empty_string
  - empty_xctest_method
  - enum_case_associated_values_count
  - expiring_todo
  - explicit_init
  - fallthrough
  - fatal_error_message
  - file_name_no_space
  - first_where
  - flatmap_over_map_reduce
  - for_where
  - force_unwrapping
  - function_default_parameter_at_end
  - ibinspectable_in_extension
  - identical_operands
  - implicit_return
  - implicitly_unwrapped_optional
  - joined_default_parameter
  - large_tuple
  - last_where
  - legacy_multiple
  - literal_expression_end_indentation
  - local_doc_comment
  - lower_acl_than_parent
  - missing_docs
  - modifier_order
  - nimble_operator
  - nslocalizedstring_key
  - nslocalizedstring_require_bundle
  - object_literal
  - opening_brace
  - operator_usage_whitespace
  - optional_enum_case_matching
  - overridden_super_call
  - override_in_extension
  - pattern_matching_keywords
  - period_spacing
  - prefer_self_type_over_type_of_self
  - prefer_zero_over_explicit_init
  - private_action
  - private_outlet
  - private_subject
  - prohibited_interface_builder
  - prohibited_super_call
  - quick_discouraged_call
  - quick_discouraged_focused_test
  - quick_discouraged_pending_test
  - reduce_into
  - redundant_nil_coalescing
  - redundant_self_in_closure
  - redundant_type_annotation
  - required_enum_case
  - return_value_from_void_function
  - self_binding
  - shorthand_optional_binding
  - single_test_class
  - sorted_enum_cases
  - sorted_first_last
  - sorted_imports
  - static_operator
  - strict_fileprivate
  - strong_iboutlet
  - superfluous_else
  - test_case_accessibility
  - toggle_bool
  - trailing_closure
  - type_contents_order
  - unavailable_function
  - unhandled_throwing_task
  - unneeded_parentheses_in_closure_argument
  - unowned_variable_capture
  - untyped_error_in_catch
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces
  - weak_delegate
  - xct_specific_matcher
  - yoda_condition

# Disabled rules
# Deprecated or requires running analyzer
# - anyobject_protocol
# - capture_variable
# - explicit_self
# - inert_defer
# - typesafe_array_init
# - unused_capture_list
# - unused_declaration
# - unused_import

# Don't enable due to preference
# - cyclomatic_complexity
# - discouraged_optional_collection
# - explicit_acl
# - explicit_enum_raw_value
# - explicit_top_level_acl
# - explicit_type_interface
# - extension_access_modifier
# - file_length
# - file_name
# - file_types_order
# - function_body_length
# - identifier_name
# - let_var_whitespace
# - multiline_arguments
# - multiline_arguments_brackets
# - multiline_function_chains
# - multiline_literal_brackets
# - multiline_parameters
# - multiline_parameters_brackets
# - no_extension_access_modifier
# - no_grouping_extension
# - no_magic_numbers
# - prefer_nimble
# - prefer_self_in_static_references
# - prefixed_toplevel_constant
# - required_deinit
# - switch_case_on_newline
# - trailing_closure
# - type_body_length
# - vertical_whitespace_between_cases

# Don't enable due to swiftformat conflict, or it's required
# - indentation_width
# - legacy_objc_type
# - number_separator
# - opening_brace
# - trailing_comma
